# Generated by Django 5.2.5 on 2025-08-23 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stylequizsubmission',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
