# Generated by Django 5.2.5 on 2025-08-23 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_stylequizsubmission_email_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stylequizsubmission',
            name='email_sent',
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('confirmed', 'Confirmed'), ('no_response', 'No Response')], default='new', max_length=20),
        ),
    ]
