# Generated by Django 5.2.5 on 2025-08-23 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_remove_stylequizsubmission_email_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stylequizsubmission',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
