# Generated by Django 5.2.6 on 2025-09-07 06:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_stylequizsubmission_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsubmission',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stylequizsubmission',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='category',
            field=models.CharField(choices=[('Wedding Favours', 'Wedding Favours'), ('Wedding Invites', 'Wedding Invites'), ('Mehndi Favours & Invites', 'Mehndi Favours & Invites'), ('House Decoration', 'House Decoration'), ('Event Management', 'Event Management'), ('Others', 'Others')], max_length=100),
        ),
    ]
